[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000245CB74F380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ba488e2939e51d616ca6d6bb17ba73af/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000245CB6FEF30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ba488e2939e51d616ca6d6bb17ba73af/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000245CB798620>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ba488e2939e51d616ca6d6bb17ba73af/screenshot