[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FAFE5DCE60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f55ab92ceb3744fdb4274f9d63f97683/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FAFE53F110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f55ab92ceb3744fdb4274f9d63f97683/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FAFE5DC8F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f55ab92ceb3744fdb4274f9d63f97683/screenshot