[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BCAB8EEBA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b4db919903fe0a6faf44ea45461f2aed/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BCAB894110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b4db919903fe0a6faf44ea45461f2aed/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BCAB8EEA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b4db919903fe0a6faf44ea45461f2aed/screenshot