[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000278CEDFB8F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/398daea9091fbc18da8d15a99e116a00/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000278CEDFBE60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/398daea9091fbc18da8d15a99e116a00/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000278CEE48110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/398daea9091fbc18da8d15a99e116a00/element