[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A6FFBB7FE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/015c5488677d6fdd4f33b6660bba3642/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A6FF5988C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/015c5488677d6fdd4f33b6660bba3642/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A6FFC080B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/015c5488677d6fdd4f33b6660bba3642/element